export 'wip/model.dart';
export 'brand_model.dart';
export 'collection_model.dart';
export 'comment_model.dart';
export 'event_model.dart';
export 'failure_model.dart';
export 'notif_model.dart';
export 'post_model.dart';
export 'user_model.dart';